# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: "Continuous Integration"

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Build and tag Docker image"
        run: $(which docker) build --tag localheinz/composer-normalize-action ${GITHUB_WORKSPACE}

      - name: "Run Docker image with default behaviour"
        run: $(which docker) run --interactive --rm --workdir=/normalizer --volume ${GITHUB_WORKSPACE}/.build:/normalizer localheinz/composer-normalize-action:latest

      - name: "Run Docker image with custom behaviour"
        run: $(which docker) run --interactive --rm --workdir=/normalizer --volume ${GITHUB_WORKSPACE}/.build:/normalizer localheinz/composer-normalize-action:latest --indent-size=1 --indent-style=tab --no-update-lock

      - name: "Docker Login"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: echo ${{ secrets.DOCKER_PASSWORD }} | $(which docker) login --password-stdin --username ${{ secrets.DOCKER_USERNAME }}

      - name: "Push Docker image (latest)"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: $(which docker) push localheinz/composer-normalize-action:latest

      - name: "Push Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: $(which docker) push localheinz/composer-normalize-action:$(bash ./.build/tag-name.sh ${GITHUB_REF})

      - name: "Docker Logout"
        if: "'refs/heads/master' == github.ref || startsWith('refs/tags/', github.ref)"
        run: $(which docker) logout
