# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request

name: "Continuous Integration"

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: localheinz/composer-normalize-action

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build Docker image"
        run: $(which docker) build --tag ${DOCKER_IMAGE}:latest .

      - name: "Run Docker image with default behaviour"
        run: $(which docker) run --interactive --rm --workdir=/app --volume ${GITHUB_WORKSPACE}/.build:/app localheinz/composer-normalize-action:latest

      - name: "Run Docker image with custom behaviour"
        run: $(which docker) run --interactive --rm --workdir=/app --volume ${GITHUB_WORKSPACE}/.build:/app localheinz/composer-normalize-action:latest --indent-size=1 --indent-style=tab --no-update-lock
