# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration"

on:
  - "pull_request"

jobs:
  docker-image:
    name: "Docker image"

    runs-on: "ubuntu-latest"

    env:
      DOCKER_IMAGE: "ergebnis/composer-normalize-action"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Build Docker image"
        run: "docker build --tag ${DOCKER_IMAGE}:latest ."

      - name: "Run Docker image with default behaviour"
        run: "docker run --interactive --rm --workdir=/app --volume ${GITHUB_WORKSPACE}/.build:/app ${{ env.DOCKER_IMAGE }}:latest"

      - name: "Run Docker image with custom behaviour, specifying options"
        run: "docker run --interactive --rm --workdir=/app --volume ${GITHUB_WORKSPACE}/.build:/app ${{ env.DOCKER_IMAGE }}:latest --diff --indent-size=1 --indent-style=space --no-update-lock"

      - name: "Run Docker image with custom behaviour, specifying argument and options"
        run: "docker run --interactive --rm --workdir=/app --volume ${GITHUB_WORKSPACE}:/app ${{ env.DOCKER_IMAGE }}:latest .build/composer.json --diff --indent-size=2 --indent-style=space  --no-update-lock"

  github-action:
    name: "GitHub Action"

    runs-on: "ubuntu-latest"

    env:
      DOCKER_IMAGE: "ergebnis/composer-normalize-action"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Copy composer.json from .build into root directory"
        run: "cp .build/composer.json composer.json"

      - name: "Run GitHub Action with default behavior"
        uses: "./"

      - name: "Run GitHub Action with custom behavior, specifying options"
        uses: "./"
        with:
          args: "--diff --indent-size=1 --indent-style=tab --no-update-lock"

      - name: "Remove composer.json from root directory"
        run: "rm composer.json"

      - name: "Run GitHub Action with custom behavior, specifying argument and options"
        uses: "./"
        with:
          args: ".build/composer.json --diff --indent-size=1 --indent-style=tab --no-update-lock"
